# Generated by Django 5.2.4 on 2025-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('length', models.IntegerField()),
                ('rna_class', models.CharField(max_length=25)),
                ('complexity', models.IntegerField()),
                ('gap', models.IntegerField()),
                ('component', models.CharField(max_length=50)),
                ('structure', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ISSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('length', models.IntegerField()),
                ('rna_class', models.CharField(max_length=25)),
                ('standard', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('match', models.IntegerField()),
                ('subsitution', models.IntegerField()),
                ('insertion', models.IntegerField()),
                ('deletion', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('length', models.IntegerField()),
                ('rna_class', models.CharField(max_length=25)),
                ('standard', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('repeat', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VNTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('length', models.IntegerField()),
                ('rna_class', models.CharField(max_length=25)),
                ('type', models.IntegerField()),
                ('repeat', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
