# Generated by Django 5.2.4 on 2025-08-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cssr',
            old_name='rna_class',
            new_name='clade',
        ),
        migrations.RenameField(
            model_name='issr',
            old_name='rna_class',
            new_name='clade',
        ),
        migrations.RenameField(
            model_name='ssr',
            old_name='rna_class',
            new_name='clade',
        ),
        migrations.RenameField(
            model_name='vntr',
            old_name='rna_class',
            new_name='clade',
        ),
    ]
